### ISSUE TITLE
Email address with single character after period not recognized

### ISSUE THREAD

**Issue by iamthad** [urbit/womb#2]
An email address like "first.m.last@site.com" isn't recognized as valid. 

It looks like the issue is at https://github.com/urbit/womb/blob/master/js/util.coffee#L99 which seems to be intended to ensure the TLD isn't too short, but also gives false negatives when there are periods in the username portion.

**Comment by galenwp** [comment]
Believe this should be fixed and deployed now.  Thanks for the bug!

**Comment by galenwp** [comment]
Whoops, and thanks for closing it.
